	-- Arquivo de apoio, caso você queira criar tabelas como as aqui criadas para a API funcionar.
	-- Você precisa executar os comandos no banco de dados para criar as tabelas,
	-- ter este arquivo aqui não significa que a tabela em seu BD estará como abaixo!

	/*
	comandos para mysql server
	*/

	CREATE DATABASE f1;
    
	USE f1;
    
	CREATE TABLE equipe (
		idEquipe INT PRIMARY KEY AUTO_INCREMENT,
		nome VARCHAR(50),
		logo VARCHAR(200)
	);

	CREATE TABLE piloto (
		idPiloto INT PRIMARY KEY AUTO_INCREMENT,
		NumPiloto INT,
		imgNumPiloto VARCHAR(200),
        imgPiloto VARCHAR(200),
		nome VARCHAR(50),
		dataNasc DATE, 
		titulos INT, 
		fkEquipe INT, 
		historia TEXT,
		FOREIGN KEY (fkEquipe) REFERENCES equipe(idEquipe)
);

	CREATE TABLE usuario (
		idUsuario INT PRIMARY KEY AUTO_INCREMENT,
		nome VARCHAR(50),
		email VARCHAR(50),
		senha VARCHAR(50),
		imgPerfil VARCHAR(100),
		fkEquipe INT,
		fkPiloto INT,
		FOREIGN KEY (fkEquipe) REFERENCES equipe(idEquipe),
		FOREIGN KEY (fkPiloto) REFERENCES piloto(idPiloto)
	);

	CREATE TABLE quiz (
	idQuiz int PRIMARY KEY AUTO_INCREMENT, 
	AnoQuiz int
	);

	CREATE TABLE tentativa(
	idQuiz int,
	idUsuario int, 
	acertos int,
	erros int,
	tempo float,
	FOREIGN KEY (idQuiz) REFERENCES quiz(idQuiz),
	FOREIGN KEY (idUsuario) REFERENCES usuario(idUsuario),
	CONSTRAINT usuarioQuiz PRIMARY KEY (idQuiz, idUsuario));

	insert into equipe values 
	(default, "Ferrari", "https://media.formula1.com/content/dam/fom-website/teams/2024/ferrari-logo.png"),
	(default, "Red Bull Racing", "https://media.formula1.com/content/dam/fom-website/teams/2024/red-bull-racing-logo.png"),
	(default, "McLaren", "https://media.formula1.com/content/dam/fom-website/teams/2024/mclaren-logo.png"),
	(default, "Mercedes", "https://media.formula1.com/content/dam/fom-website/teams/2024/mercedes-logo.png"),
	(default, "Aston Martin", "https://media.formula1.com/content/dam/fom-website/teams/2024/aston-martin-logo.png"),
	(default, "Visa RB", "https://media.formula1.com/content/dam/fom-website/teams/2024/rb-logo.png"),
	(default, "Haas", "https://media.formula1.com/content/dam/fom-website/teams/2024/haas-logo.png"),
	(default, "Williams","https://media.formula1.com/content/dam/fom-website/teams/2024/williams-logo.png"),
	(default, "Alpine","https://media.formula1.com/content/dam/fom-website/teams/2024/alpine-logo.png"),
	(default, "Kick Sauber", "https://media.formula1.com/content/dam/fom-website/teams/2024/kick-sauber-logo.png");

	insert into piloto values 
	(1, 16, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CHALEC01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png", "Charles Leclerc", "1997-10-16", null, 1, "Nascido no idílio mediterrâneo de Mônaco, Leclerc chegou à F1 em uma onda de expectativa. Praticamente imbatível em seu caminho para os títulos da GP3 e da Fórmula 2, ele mostrou uma variedade deslumbrante de habilidades, desde pole positions arrasadoras, vitórias comandadas - mesmo quando seu carro pegou fogo duas vezes em Silverstone - até uma capacidade de abrir caminho pelo pelotão. Ganhar campeonatos consecutivos também ensinou Leclerc a lidar com a pressão, outra ferramenta útil no grande palco do automobilismo da Fórmula 1. Ao subir para a F1 em 2018, Leclerc mostrou lampejos de velocidade explosiva aos sábados e brilhantismo em corridas aos domingos, levando sua Sauber além de seus limites - e garantindo um lugar na Ferrari para 2019, entrando nos sapatos do último campeão mundial da Scuderia, Kimi Raikkonen. Lá, ele imediatamente causou alvoroço, sem medo de duelar roda a roda com o estabelecido número um, Sebastian Vettel. Uma vitória inaugural na F1 em Spa foi seguida por outra uma semana depois no sagrado solo da Ferrari em Monza. Os tifosi haviam encontrado um novo herói - que então se tornou o primeiro homem a superar Vettel em pontuação ao longo de uma temporada com a Scuderia, façanha que repetiu de maneira esmagadora no ano seguinte. As temporadas de 2020 e '21 renderam pouco fruto para a Ferrari, mas Leclerc manteve sua determinação para emergir como verdadeiro candidato ao título em 2022. Com três vitórias, 11 pódios e nove pole positions, ele foi o único capaz de consistentemente enfrentar o campeão Max Verstappen - uma façanha que ele e a Scuderia infelizmente não conseguiram repetir em 2023. Fora do carro, Leclerc é modesto e ponderado - mas então ele está em sua própria missão muito pessoal. Este emocionante jovem talento está correndo em homenagem ao seu falecido pai Hervé e ao seu amigo e mentor Jules Bianchi, o piloto de F1 que morreu em 2015. Pelos resultados até agora, ele está deixando ambos orgulhosos."),
    (2, 55, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CARSAI01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png", "Carlos Sainz", "1994-09-01", null, 1, "Ele é o matador da realeza das corridas de Madrid. Depois de entrar no 'Bull Ring' da F1 ao lado de Max Verstappen na Toro Rosso em 2015, Sainz rapidamente mostrou seu espírito combativo. Um corredor tenaz, ele leva o carro ao limite enquanto avança pelo pelotão. Não é de admirar que Sainz tenha ganho o apelido de Chilli. Mas o espanhol é inteligente além de instintivo, pensando durante uma corrida e alcançando pontos. Este temperamento calmo o segue fora da pista, onde ele permanece imperturbável pelas pressões de forjar uma carreira de Grand Prix com um nome famoso. Sainz é filho do bicampeão mundial de rali, também seu homônimo, e trouxe algumas das habilidades de direção do pai para o circuito da F1 - o junior adora uma deliciosa dose de derrapagem, para dizer o mínimo. Depois de seguir os passos de seu famoso pai, Sainz teve grandes botas de corrida para preencher - primeiro na McLaren, onde substituiu seu herói de infância, Fernando Alonso, e agora na Ferrari, no assento anteriormente ocupado por Sebastian Vettel. Nunca é fácil viver à sombra de gigantes do esporte, mas Sainz mostrou a determinação e a disposição para lidar com isso - ele conquistou uma vitória no Grande Prêmio em ambas as suas temporadas com a Scuderia até o momento. Vamos!"),
    (3, 33, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/MAXVER01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png", "Max Verstappen", "1997-09-30", 3, 2, "Ele é Max por nome e Max por natureza. Chegando como o mais jovem competidor da história da Fórmula 1 com apenas 17 anos, Verstappen levou seu carro, seus rivais e os livros de recordes do esporte ao limite. O holandês de rosto jovem com o coração de um leão assumiu o controle da Toro Rosso - e depois da Red Bull - com seu estilo de pilotagem instintivo. O mais jovem pontuador da F1 logo se tornou o mais jovem vencedor de corridas - aos 18 anos e 228 dias - com uma corrida oportunista, mas controlada, em sua estreia pela Red Bull em Barcelona 2016. Um verdadeiro piloto roda a roda, outra corrida impressionante no Brasil, saindo do final do pelotão para o pódio em uma pista molhada e traiçoeira, manteve os elogios chegando. A atitude sem restrições de Verstappen e sua defesa dura às vezes o colocaram em águas turbulentas com seus colegas e patrocinadores. Mas os erros que inicialmente prejudicaram seu potencial deram lugar à maturidade, enquanto o bravado e a energia que o tornam um talento espetacular permaneceram - e as vitórias continuaram chegando. Elas o levaram ao seu primeiro título de pilotos da F1 após aquele agora lendário confronto final com Lewis Hamilton em 2021. Ele seguiu isso com uma poderosa defesa de título em 2022, antes de um épico terceiro triunfo consecutivo no campeonato, apresentando um recorde de 19 vitórias em 23 Grandes Prêmios. Filho do ex-piloto de F1 Jos Verstappen e da super-rápida mãe de kart, Sophie Kumpen, a corrida corre em suas veias. Apesar de ter saído da casa do pai para morar em Mônaco, Verstappen permanece próximo à sua família, e embora não tenha medo de falar o que pensa, ele ainda pode ser surpreendentemente tímido. Tendo se tornado o primeiro campeão mundial da Holanda aos apenas 24 anos, as expectativas para a principal estrela da nova geração são altíssimas - mas com Verstappen, há uma sensação de que o céu é o limite."),
    (4, 11, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/SERPER01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png", "Sergio Perez", "1990-01-26", null, 2, "Ele é o lutador com um toque gentil da terra da Lucha Libre. A reputação de Pérez na F1 foi construída com abordagens opostas às corridas de Grand Prix. Por um lado, ele é um combatente agressivo que luta seu caminho pelo pelotão e para os pontos. Nunca com medo de adicionar um pouco de tempero aos seus encontros na pista, até mesmo seus companheiros de equipe nem sempre escapam do calor do mexicano. Por outro lado, Pérez é um operador suave, um mestre em gerenciar pneus para extrair desempenho extra e dar-lhe vantagem na estratégia. Um favorito firme no grid após seu tempo com Sauber, McLaren, Force India e Racing Point, Pérez amadureceu em um piloto analítico e jogador de equipe. Um compatriota orgulhoso, o pistoleiro de Guadalajara acumulou mais pontos do que qualquer outro mexicano na história da F1. Em Sakhir 2020, ele também igualou seu herói e compatriota Pedro Rodriguez ao cruzar a bandeira quadriculada em primeiro lugar - uma performance que lhe rendeu um lugar com os concorrentes ao título da Red Bull. Lá, ele desempenhou um papel de apoio nas campanhas de campeão de Verstappen em 2021/22/23, também adicionando mais cinco vitórias ao seu próprio saldo pessoal. Seu próprio desafio pelo título pode não ser garantido, especialmente com Verstappen como companheiro de equipe, mas Pérez trabalhando duro e correndo com o coração estão."),
    (5, 4, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANNOR01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png", "Lando Norris", "1999-11-13", null, 3, "Lando Norris pode não ser nomeado em homenagem ao rebelde de Star Wars, Lando Calrissian - sua mãe simplesmente gostava do nome - mas ele tem talento e espírito de luta em abundância. A McLaren tinha o adolescente britânico em seus livros por dois anos antes de acelerá-lo para a galáxia de estrelas da F1 em 2019. Um foguete em sua carreira júnior, com uma inclinação para pole positions e lutas roda a roda, Norris não decepcionou. Ao lado do altamente avaliado - e muito mais experiente - Carlos Sainz, sua temporada de estreia foi impressionante, Norris superando o espanhol na batalha de classificação direta, marcando pontos 11 vezes e perdendo por pouco um lugar no top 10 do campeonato. Um primeiro pódio veio em 2020, com mais seguindo nas duas temporadas subsequentes - ele perdeu por pouco uma vitória na Rússia em 2021 - enquanto ele dominava outro companheiro de equipe mais experiente, Daniel Ricciardo, para firmar seu lugar na elite da F1. Fora da pista, Norris transborda com um charme modesto e um lado artístico que o vê desenhar e pintar seu próprio equipamento de corrida como um hobby. O foco para o futuro é aliar arte e ambição na pista, enquanto a McLaren conta com a promessa da juventude para levá-los de volta ao topo. Norris espera que a força aerodinâmica esteja com ele..."),
    (6, 81, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/OSCPIA01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png", "Oscar Piastri", "2001-06-04", null, 3, "Nascido em Melbourne, a poucos passos do local do Grande Prêmio da Austrália, os sonhos de um jovem Oscar Piastri de um dia correr na Fórmula 1 foram alimentados pelos pilotos estrelas do esporte rugindo pelas ruas locais, também conhecidas como Albert Park. Mas seria necessário um enorme comprometimento e sacrifício para transformar esse sonho em realidade, com uma mudança para a Europa - feita pelos compatriotas Mark Webber e Daniel Ricciardo antes dele - como o único caminho para competir contra os melhores e chamar a atenção dos tomadores de decisão do esporte. Usando o sucesso na cena do karting australiano como um trampolim, Piastri continuou a aprender o ofício em campeonatos por toda a Europa, antes de ter seu primeiro contato com a competição de monopostos aos 15 anos - dois pódios na F4 UAE foram um sinal do que estava por vir. A partir daí, o sucesso fluiu. Vice-campeão da F4 britânica. Campeão da Formula Renault. Campeão da F3. Campeão da F2 (com mais de 50 pontos de vantagem). Piastri não apenas subiu a escada das categorias de base, ele a escalou rapidamente para bater à porta da F1 com força. Tão impressionante foi Piastri que duas equipes de F1 disputaram seus serviços para 2023, adicionando uma nova dimensão ao mercado de pilotos e à chamada silly season. A McLaren, e não os apoiadores de longa data Alpine, levaram a melhor e seu novato retribuiu em dobro, conquistando dois pódios em uma estreia altamente impressionante."),
    (7, 44, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LEWHAM01.png", "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png", "Lewis Hamilton", "1985-01-07", 7, 4, "Still I Rise - são as palavras estampadas na parte de trás do capacete de Lewis Hamilton e tatuadas em seus ombros, e desde que aniquilou as expectativas com uma das maiores performances de estreia na história da F1 em 2007, é literalmente tudo o que ele tem feito: subido ao topo da lista de pole positions de todos os tempos à frente de seu herói Ayrton Senna, avançado para o primeiro lugar na lista de vitórias ultrapassando o inimitável Michael Schumacher e depois igualado aos sete títulos mundiais do lendário alemão. Ele é o G.O.A.T? Poucos negariam que ele está na conversa - e o que é mais, ele chegou lá do seu jeito, combinando sua velocidade implacável com uma recusa em se conformar com estereótipos sobre como um piloto de corrida deve pensar, se vestir ou se comportar. O respeito é conquistado com dificuldade na F1, mas Hamilton - Sir Lewis Hamilton para ser preciso - o tem de todos os seus pares. Por quê? Porque eles sabem que, seja qual for a pista, seja qual for a condição, seja qual for a situação, quando seu visor desce e as luzes se apagam, é a hora de Hamilton."),
	(8, 63, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GEORUS01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png", "George Russell", "1998-02-15", null, 4, "Ele é o piloto com o lema: 'Se tiver dúvida, vá com tudo'. George Russell viveu por esse lema ao longo de sua carreira na F1 até o momento, superando o experiente companheiro de equipe Robert Kubica em todas as 21 corridas de sua temporada de estreia, levando a Williams de volta ao pódio em 2021 e conquistando sua primeira vitória com a Mercedes em 2022. Essa brilhante velocidade de base serviu Russell bem enquanto acumulava títulos em seu caminho para a Fórmula 1. O britânico conquistou o campeonato de GP3 em 2017 e entregou a coroa da Fórmula 2 em 2018 sob imensa pressão. Percebendo seu potencial, os campeões mundiais da Mercedes correram para assiná-lo para seu programa júnior em 2017, quando Russell já tinha um acordo de DTM à mesa. Ele acumulou mais experiência com sessões de treinos livres com a Force India e testes para as Flechas de Prata, antes de conquistar sua vaga de corrida na Williams com motor Mercedes. Uma recusa em ceder terreno para seus rivais - e o compromisso com uma ultrapassagem difícil - sustenta a mentalidade vencedora de Russell. E foi isso que o levou a ser convocado para substituir Lewis Hamilton em uma participação única pela Mercedes no Grande Prêmio de Sakhir de 2020, quando o campeão reinante foi atingido pelo Covid-19. Essa atuação estelar viu Russell perder a pole por apenas 0,026s e depois superar o veterano da Mercedes, Valtteri Bottas. Apenas uma parada nos boxes malfeita e um doloroso furo de pneu tardio impediram uma vitória quase certa para o emergente super substituto. Ele manteve a cabeça baixa na Williams em 2021, marcando seus primeiros pontos e pódio, sempre mantendo o olho no prêmio maior. Tendo se provado um trabalhador árduo e um talento tenaz, esse prêmio chegou na forma de uma chance de enfrentar o compatriota e heptacampeão Hamilton em máquinas idênticas. Foi uma oportunidade que Russell aproveitou ao máximo, e ele conquistou sua primeira vitória na F1 - e a única vitória da Mercedes em 2022 - no Brasil. A temporada de 2023 provou ser mais difícil, mas se as Flechas de Prata conseguirem se recuperar e fornecer um carro verdadeiramente competitivo, uma disputa pelo título certamente se aproxima. Um desafio enorme, mas como sempre, 'Russell, o Foguete', estará indo com tudo."),
	(9, 14, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/FERALO01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png", "Fernando Alonso", "1981-07-29", 2, 5, "Michael Schumacher foi o rei indiscutível da Fórmula 1 no início dos anos 2000, conquistando vitórias e campeonatos a uma taxa simplesmente inédita na época. Seria preciso alguém muito especial para derrubar a lenda da Ferrari do seu trono - e o fato de ser Fernando Alonso quem o fez, diz tudo o que você precisa saber sobre o espanhol. Ferozmente competitivo, Alonso não é tímido sobre seu talento, classificando-se como 9/10 'em tudo', e poucos que o conhecem discordariam, com suas performances na F1 sendo caracterizadas por velocidade avassaladora, pensamento tático brilhante, habilidade de corrida exemplar, um olho afiado para detalhes e uma determinação implacável para vencer. Um quebrador de recordes em série em seus primeiros dias, ele foi - em um momento - o piloto mais jovem a conquistar uma pole position, vencer uma corrida, ser campeão mundial e bicampeão mundial, enquanto engolia sucesso com a equipe Renault. Mesmo Alonso não conseguiu continuar essa incrível sequência em sua carreira posterior, não conseguindo adicionar outro título à sua coleção apesar de passagens pela McLaren e Ferrari. Mas após dois anos afastado das corridas de Fórmula 1 - e com duas vitórias em Le Mans no currículo - Alonso retornou com a Alpine em 2021. Sua velocidade e determinação intactas, ele voltou ao pódio naquele ano, mas frustrado pela má confiabilidade - e pela falta de um contrato de longo prazo - na temporada seguinte, optou por mudar de equipe mais uma vez. E depois de oito pódios em sua primeira temporada com a Aston Martin, Alonso agora espera que seja com a equipe em verde que ele finalmente retorne às vitórias, já que ele tem assuntos inacabados com a F1..."),
	(10, 18, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANSTR01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png", "Lance Stroll", "1998-10-29", null, 5, "Para Stroll, não existe tal coisa como 'muito rápido, muito cedo', um adolescente sensação com uma predileção por corridas sob chuva. Um dos jovens descolados no grid, Stroll foi revelado pouco depois de completar 18 anos pela Williams - antes mesmo de terminar o ensino médio e obter sua licença de motorista. Stroll estava determinado em sua temporada de estreia em 2017, estabelecendo recordes pelo caminho. Um piloto oportunista, ele subiu ao pódio em Baku, o mais jovem estreante a fazê-lo. Como filho de um empresário rico, Stroll está acostumado a um estilo de vida de champanhe, mas agora ele sabe que o sabor da espuma é ainda mais doce no pódio. Depois, em Monza, ele dominou as chuvas para se tornar o piloto mais jovem da história a largar na primeira fila. Determinado desde o início, o canadense adora ganhar posições na primeira volta e lutar até os pontos. Stroll tem o potencial para ser uma presença de longo prazo na Fórmula 1 - como amplamente ilustrado por sua primeira pole position e outros dois pódios em 2020. Isso veio depois que seu pai, Lawrence, liderou o consórcio que assumiu a Force India no meio da temporada de 2018 e depois a transformou de Racing Point para Aston Martin em 2021. O futuro parece brilhante tanto para a equipe quanto para seu jovem piloto - e mesmo que chova, Stroll pode continuar acelerando na ponta do pelotão."),
	(11, 22, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/YUKTSU01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png", "Yuki Tsunoda", "2000-05-11", null, 6, "Na história inteira da Fórmula 1, nenhum piloto japonês jamais venceu um Grande Prêmio do Campeonato Mundial. Yuki Tsunoda poderia ser o primeiro? A Red Bull certamente pensa assim, com o jovem muito no caminho para sua equipe principal se ele continuar a impressionar como tem feito nos últimos anos. A ascensão de Tsunoda ao topo do automobilismo foi surpreendentemente rápida: ele passou de correr na F4 japonesa para um assento na Fórmula 1 com a AlphaTauri, agora RB, em pouco mais de três anos, depois de ter chegado à Europa em 2019 sem conhecimento das pistas. Mas depois de um começo lento na F3, seguido por uma campanha de estreia na F2 muito impressionante que o viu terminar em terceiro no campeonato e conquistar três vitórias pelo caminho, Tsunoda provou que tinha a velocidade e a habilidade de corrida para conquistar seu lugar no grid da F1. Ele pode não ter se adaptado às corridas de Grand Prix tão rapidamente quanto se adaptou à F2, mas agora que ele se estabeleceu firmemente na Fórmula 1, ele ainda pode se encontrar lutando na ponta do pelotão em um Red Bull."),
	(12, 3, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/DANRIC01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png", "Daniel Ricciardo", "1989-07-01", null, 6, "O autodenominado 'Honey Badger' é fofo por fora e briguento por dentro. Pilotos, cuidado, porque por trás da persona descontraída e do grande sorriso de Ricciardo está um piloto afiado com uma mordida. O australiano combina velocidade máxima com uma habilidade de corrida impressionante. Nunca com medo de ir ao limite se isso significar realizar uma ultrapassagem, Ricciardo é um vencedor comprovado, capaz de terminar consistentemente na parte superior da tabela do campeonato quando tem o equipamento certo. Um regular no pódio em seus dias com a Red Bull, Ricciardo batizou os degraus ao redor do mundo com um toque da cultura australiana - o 'Shoey' - enquanto tomava champanhe de uma bota de corrida encharcada. Sim, é bobo, mas a celebração característica ilustra por que ele é amado por seu senso de humor, mas nunca subestimado na pista. As próximas mudanças de sua carreira para a equipe de fábrica da Renault em 2019 e depois para a McLaren em 2021 trouxeram novos desafios para o piloto de Perth, mas não conseguiram realizar seu sonho de seguir Jack Brabham e Alan Jones como o próximo campeão mundial da Austrália - e o deixaram fora da grade para o início de 2023. Mas ele logo encontrou um caminho de volta, voltando à Red Bull em um papel de terceiro piloto e impressionando o suficiente para garantir um lugar na equipe irmã AlphaTauri, agora RB, a partir da metade da temporada. O retorno foi inicialmente breve - uma mão quebrada de um acidente nos treinos o excluiu de cinco Grandes Prêmios - mas quando ele retornou, a velha velocidade estava lá. Um futuro como companheiro de equipe de Max Verstappen agora estará em sua mira, mas aconteça o que acontecer a seguir, Ricciardo certamente continuará sorrindo."),
	(13, 27, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/NICHUL01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png", "Nico Hülkenberg", "1987-08-19", null, 7, "Ele é o Super-herói com o talento para se tornar uma estrela das corridas - se ao menos pudesse mostrar seu potencial com uma equipe de ponta. O 'Hulk' da F1 mostrou uma força e resistência incríveis como um invasor do meio-campo para Williams, Force India, Sauber, Renault, Racing Point, Aston Martin e Haas durante uma carreira que remonta a 2010. Naquela temporada de estreia, Hulkenberg dominou as condições de pista em mudança para conquistar uma brilhante pole position no Brasil, mostrando que tinha cérebro além de músculos. Desde então, sua habilidade de acumular consistentemente pontos o tornou um jogador de equipe altamente valorizado. Em 2015, sua reputação cresceu ainda mais quando, em um fim de semana longe de seu emprego diurno, ele venceu a clássica corrida das 24 Horas de Le Mans pela Porsche na primeira tentativa. O alter ego de Hulkenberg fora da pista é pé no chão - ele é o tipo de piloto que segura seu próprio guarda-chuva quando está chovendo a caminho do grid - com um senso de humor malicioso. Quando ele alcançou o recorde indesejado de mais largadas sem um pódio, ele riu como o início da 'era Hulkenberg'. Felizmente, mesmo depois de ser dispensado pela Renault no final de 2019, a era do popular alemão continuou com algumas corridas de substituição (e destacadas) em 2020 e 2022, e depois de garantir um retorno em tempo integral à F1 com a Haas, o 'Hulk' abraçou outra chance de acertar as coisas."),
	(14, 20, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/KEVMAG01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KEVMAG01_Kevin_Magnussen/kevmag01.png", "Kevin Magnussen", "1992-10-05", null, 7, "Chame-o de solitário ou de rebelde, mas Magnussen está na Fórmula 1 por um único motivo - para correr. Ele pode ser um piloto de segunda geração da F1 - seguindo os passos de seu pai, Jan, no grid - mas os ídolos de Magnussen são da 'era dourada' do automobilismo, quando nomes como Juan Manuel Fangio e Stirling Moss arriscavam tudo pelo amor ao esporte. A própria habilidade do piloto de Roskilde foi comprovada em sua estreia pela McLaren, que o orientou nas categorias de base, quando ele chegou ao pódio no terceiro lugar no Grande Prêmio da Austrália de 2014, tornando-se o primeiro dinamarquês a conquistar um pódio na F1. Outros momentos memoráveis foram mais difíceis de encontrar, pois ele deixou a McLaren para trás por uma temporada na Renault, antes de se estabelecer por quatro temporadas entre espíritos afins na Haas. Após um ano nos Estados Unidos, competindo na Indy e em carros esportivos, entre outras coisas, ele retornou à equipe americana em 2022, garantindo a primeira pole position da equipe no Grande Prêmio do Brasil. Suas manobras ousadas e sua abordagem agressiva lhe renderam uma reputação de bad boy na pista, algo que ainda o deixa perplexo. Fora do carro, Magnussen é descontraído e afável. Afinal, ele tem o emprego dos sonhos - e está aqui apenas para correr."),
	(15, 23, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ALEALB01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png", "Alexander Albon", "1996-03-23", null, 8, "Nascido em Londres, mas competindo sob a bandeira da Tailândia, a primeira palavra de Alexander Albon foi na verdade italiana. Essa palavra foi Ferrari - embora tenha sido com outra equipe italiana que ele teve sua grande chance na F1. Idolatrando Michael Schumacher e sonhando em um dia correr na Fórmula 1, o jovem Albon foi superado pelo título da GP3 em 2016 por um certo Charles Leclerc. Ele então deixou sua grande amizade com George Russell à beira da pista enquanto levava a luta pelo título da Fórmula 2 de 2018 até o final. Graduando-se para a grande liga da F1 junto com mais um contemporâneo - Lando Norris - em 2019, Albon fez sua fala na pista com a Toro Rosso nas primeiras corridas, conquistando uma promoção no meio da temporada para a Red Bull Racing. Um ultrapassador estiloso com uma mentalidade de campeão, Albon não se abalou ao ser parceiro de Max Verstappen na segunda metade de sua temporada de estreia, alcançando seis primeiras posições em oito de suas nove corridas de 2019 com a Red Bull. Manter-se em contato com o futuro campeão foi mais difícil em 2020 e a Red Bull o retirou de sua formação de pilotos. No entanto, Albon foi crucialmente mantido como piloto de teste e reserva, mantendo-o muito presente no radar dos chefes de equipe, levando ao seu retorno em 2022 à grid com a Williams, onde ele estabeleceu uma reputação como um qualificador rápido e piloto maduro. Descontraído e alegre, com um sorriso travesso, o piloto tailandês é popular entre seus pares - nem sempre fácil no caldeirão de competição do automobilismo - mas você não tem sucesso na Fórmula 1 sendo popular. O desafio de Albon continua sendo grande - aproveitar ao máximo uma rara segunda oportunidade na F1."),
	(16, 24, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LOGSAR01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LOGSAR01_Logan_Sargeant/logsar01.png", "Logan Sargeant", "2000-12-31", null, 8, "Logan Sargeant se tornou o primeiro piloto americano da Fórmula 1 em quase oito anos quando entrou na pista para a temporada de 2023, dando ao país um favorito da casa para torcer mais uma vez. Um prolífico vencedor de títulos no kartismo, a glória do campeonato escapou de Sargeant depois que ele fez a transição para as corridas de monopostos, mas pole positions e vitórias em quase todas as categorias que ele disputou destacaram sua velocidade bruta e potencial. Na verdade, terminar em segundo lugar no F4 UAE, em terceiro no British F4 e em terceiro na F3 (tendo também subido ao pódio no prestigioso Grande Prêmio de Macau) mostrou que ele poderia estar lá ou perto em uma variedade de campeonatos, com muito potencial ainda a ser explorado. Isso também convenceu a Williams a adicionar o jovem piloto ao seu rol de talentos quando ele alcançou a F2, onde mais vitórias e outra classificação entre os três primeiros em 2022 garantiram os pontos necessários para a Super Licença e completar a jornada e se formar na F1 com a equipe Grove para 2023. Desde as cinco aparições de Alexander Rossi com a equipe Manor no final da temporada de 2015, nenhum americano havia estado no grid da F1, e Sargeant gostou de mudar isso ao longo de sua primeira temporada, mesmo que, no papel, um único ponto fosse sua única recompensa. E com três corridas nos EUA agora no calendário da Fórmula 1 - Miami, Austin e Las Vegas - a mais recente estrela da F1 americana sabe que será incentivado por muito apoio em casa."),
	(17, 10, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/PIEGAS01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png", "Pierre Gasly", "1996-02-07", null, 9, "Se há alguém que sabe o quão grande pode ser o passeio de montanha-russa na carreira de um piloto de F1, é Pierre Gasly! O francês voador foi convocado para fazer sua estreia em 2017 na Malásia no lugar de Daniil Kvyat e, após provar seu valor, foi nomeado piloto da Toro Rosso no ano seguinte. Mais 21 corridas em sua carreira inicial, Gasly foi promovido novamente - desta vez para substituir o grande nome da Red Bull, Daniel Ricciardo. Gasly parecia ter o dom de estar no lugar certo na hora certa - uma qualidade igualmente útil na pista. Uma série de impressionantes performances em 2018 para a Toro Rosso - incluindo um brilhante quarto lugar no Bahrein - mostraram uma promessa emocionante para o que ele poderia fazer com a equipe 'A' em 2019. Infelizmente, essa promessa apareceu apenas em flashes - e ele rapidamente sofreu com comparações desfavoráveis com o superastro companheiro de equipe Max Verstappen. Tanto que, após a pausa de verão, ele foi enviado de volta para a Toro Rosso, com outro jovem promissor - Alex Albon - recebendo uma chance no assento 'sênior' da Red Bull. Mas Gasly se recuperou, como só Gasly pode fazer. Nas nove corridas restantes da temporada, ele marcou quase tantos pontos quanto o companheiro de equipe Kvyat conseguiu durante todo o ano - e conquistou seu melhor resultado em corrida com o P2 no Brasil. Essa trajetória continuou em 2020, atingindo o auge com uma emocionante vitória no GP da Itália, e não diminuiu em 2021, quando voltou ao pódio e marcou 110 dos 142 pontos da equipe. Quando o momentum da AlphaTauri estagnou em 2022, Gasly decidiu que era hora de uma mudança - na forma da equipe francesa Alpine, com o compatriota - e antigo adversário - Esteban Ocon como companheiro de equipe. A questão agora é se ele pode recuperar o momentum e ter outra chance na grandeza da F1..."),
	(18, 31, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ESTOCO01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png", "Esteban Ocon", "1996-09-17", null, 9, "Se há uma palavra que domina a carreira de Esteban Ocon, é 'sacrifício'. Quando ele era apenas um promissor piloto de kart, os pais de Ocon venderam a casa, suspenderam seus empregos e começaram uma vida na estrada, vivendo em um trailer e viajando de circuito em circuito para apoiar a carreira em ascensão de seu filho. Sacrifício, veja bem - mas funcionou. Em 2014, Ocon teve seu grande avanço no mundo dos monopostos, quando derrotou um certo Max Verstappen para conquistar o título da Fórmula 3 Europeia. Apoiado pela Mercedes, ele conquistou o título da GP3 no ano seguinte e estava na metade de uma temporada da DTM em 2016 quando recebeu a oportunidade de substituir Rio Haryanto na equipe Manor a partir do Grande Prêmio da Bélgica em diante. Essa oportunidade levou a um assento em tempo integral no ano seguinte com a Force India, onde suas batalhas roda a roda com o altamente conceituado companheiro de equipe Sergio Perez rapidamente o marcaram como uma estrela em ascensão. Mas quando Lawrence Stroll, pai do piloto Lance, interveio no meio de 2018 para garantir o futuro financeiro da equipe, o destino de Ocon estava selado, sendo afastado no final do ano para permitir que Stroll Jnr se juntasse vindo da Williams. Ocon esperou seu momento, no entanto, e após um ano como piloto reserva da Mercedes, ele encontrou seu caminho de volta para um assento de corrida para 2020 com a Renault, que se tornou Alpine para 2021 - quando sua espera finalmente valeu a pena, ao conquistar sua - e a primeira vitória da famosa marca francesa - na Fórmula 1. Nada na carreira de automobilismo de Ocon veio fácil - mas se ele conseguiu retornar ao grid da F1 e subir ao pódio, foi através de uma combinação de autoconfiança, determinação e um talento que está entre os melhores."),
	(19, 77, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/VALBOT01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png", "Valtteri Bottas", "1989-08-28", null, 10, "Aprendendo seu ofício nas estradas finlandesas de gelo e neve, ele nasceu para ser um piloto de Grand Prix. Bottas explica que se você pode dirigir nas estradas congeladas de sua terra natal, então você pode dirigir em qualquer lugar. E há também a mentalidade finlandesa - reservada, diligente e calma, a pista rápida da F1 não o intimida. Fazendo sua estreia na F1 com a Williams em 2013, Bottas logo se tornou parte da família. Pontos e pódios se seguiram com o piloto confiável até acumulando mais pontos sem uma vitória, um recorde que ele ressentia, mas que mostrava sua habilidade. O fato de o finlandês ser uma máquina de pontos o viu ser promovido de repente para o assento mais cobiçado na F1 - o assento vago de campeão da Mercedes de Nico Rosberg. Bottas floresceu na Mercedes em 2017, liberando seu ritmo para acumular pole positions e vitórias pessoais, bem como um campeonato de equipe para a famosa marca Mercedes ao lado de Lewis Hamilton. Ele até empatou com Hamilton e Sebastian Vettel com 13 pódios. Para um cara tímido, isso trouxe um impulso de confiança e um novo swagger - embora de uma maneira muito discreta e finlandesa. Ele precisaria de toda essa confiança em 2018 - uma temporada que Bottas descreveu como a pior de sua carreira na F1, já que ele não conquistou nenhuma vitória em comparação com as 11 de Hamilton. No entanto, isso foi mais um reflexo do brilhantismo de seu companheiro de equipe do que de quaisquer deficiências de sua parte. Bottas elevou o nível em 2019, com quatro vitórias garantindo um convincente segundo lugar no campeonato atrás de Hamilton, mas isso caiu para duas vitórias em comparação com as 11 de seu companheiro de equipe em 2020 e depois apenas uma em 2021, levando a Mercedes a dispensá-lo após cinco temporadas. Em 2022, ele começou um novo capítulo em sua carreira na F1, substituindo o compatriota Kimi Raikkonen para liderar uma nova formação na Alfa Romeo, agora Kick Sauber, e mentorando o estreante chinês Zhou Guanyu."),
	(20, 24, 'https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GUAZHO01.png', 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GUAZHO01_Guanyu_Zhou/guazho01.png', 'Zhou Guanyu', '1999-05-30', NULL, 10, 'A China nunca havia contado com um piloto de Grande Prêmio entre seus cidadãos - até que Zhou Guanyu mudou esse estado de coisas, depois de receber a convocação para fazer sua estreia na F1 pela Alfa Romeo, agora Kick Sauber, em 2022. O piloto nascido em Xangai compareceu ao Grande Prêmio inaugural de sua cidade natal em 2004, aos cinco anos de idade, torcendo por seu herói Fernando Alonso. Mas, tendo pego o vírus das corridas, o piloto chinês então se propôs o ambicioso objetivo de se tornar o primeiro piloto de Fórmula 1 de seu país - conquistando um feito que Ma Qinghua, o único outro piloto chinês a participar de um fim de semana da Fórmula 1, nunca conseguiu. Demonstrando audácia e dedicação, Zhou colocou seu plano em ação ao se mudar para a Inglaterra com sua família aos apenas 12 anos de idade para perseguir suas ambições no automobilismo. Um segundo lugar no campeonato italiano de F4 de 2015 provou que Zhou possuía o que era necessário - um fato já observado pela Ferrari, que o havia contratado para sua academia de pilotos um ano antes. Uma mudança para a academia da Renault em 2019 coincidiu com sua estreia na Fórmula 2, com Zhou construindo sua confiança na série por meio de múltiplas vitórias e pole positions ao longo de três temporadas, levando-o a desafiar pelo título de pilotos em 2021. Isso foi o suficiente para convencer o Chefe de Equipe Fred Vasseur a depositar sua confiança em Zhou para 2022 e colocá-lo ao lado do ex-piloto da Mercedes, Valtteri Bottas - permitindo que Zhou realizasse seu sonho de correr na F1, e até mesmo ver como ele se sai contra seu próprio herói de infância, Fernando Alonso.'),
    (21, 38, 'https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/OLIBEA01.png', 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png', 'Oliver Bearman', '2005-05-08', NULL, 1, 'Ele é o reserva oficial da Ferrari e fez sua estreia em corridas de Fórmula 1 na Arábia Saudita no lugar do Carlos Sainz, que estava com apendicite. Bearman, de 18 anos, teve seu primeiro contato com máquinas da F1 com a Scuderia no final do ano passado, em preparação para duas participações nos treinos livres 1 para a equipe Haas nos Grandes Prêmios do México e Abu Dhabi. Desde então, ele completou várias sessões de teste na F1 e atualmente está competindo na Fórmula 2 com a equipe Prema Racing, tendo vencido quatro corridas e ficado em sexto na classificação da série de acesso no ano passado. Após um início difícil da temporada de 2024 para a Prema no Bahrein, Bearman reagiu e conquistou a pole position no rápido circuito de Jeddah, mas, com as obrigações de substituição de Sainz, ele precisou temporariamente abandonar seus compromissos na F2. Não que ele estivesse reclamando - uma performance impressionante viu o jovem inglês marcar seis pontos pelo sétimo lugar em seu primeiro Grande Prêmio, aumentando significativamente suas perspectivas futuras na Fórmula 1.');
        
        
        
        

		
		