	-- Arquivo de apoio, caso você queira criar tabelas como as aqui criadas para a API funcionar.
	-- Você precisa executar os comandos no banco de dados para criar as tabelas,
	-- ter este arquivo aqui não significa que a tabela em seu BD estará como abaixo!

	/*
	comandos para mysql server
	*/

	CREATE DATABASE f1;
    
	USE f1;
    
	CREATE TABLE equipe (
		idEquipe INT PRIMARY KEY AUTO_INCREMENT,
		nome VARCHAR(50),
		logo VARCHAR(200),
        imgCarro VARCHAR(200),
        historia TEXT
	);

	CREATE TABLE piloto (
		idPiloto INT PRIMARY KEY AUTO_INCREMENT,
		NumPiloto INT,
		imgNumPiloto VARCHAR(200),
        imgPiloto VARCHAR(200),
		nome VARCHAR(50),
		dataNasc DATE, 
		titulos INT, 
		fkEquipe INT, 
		historia TEXT,
		FOREIGN KEY (fkEquipe) REFERENCES equipe(idEquipe)
);

	CREATE TABLE usuario (
		idUsuario INT PRIMARY KEY AUTO_INCREMENT,
		nome VARCHAR(50),
		email VARCHAR(50),
		senha VARCHAR(50),
		imgPerfil VARCHAR(100),
		fkEquipe INT,
		fkPiloto INT,
		FOREIGN KEY (fkEquipe) REFERENCES equipe(idEquipe),
		FOREIGN KEY (fkPiloto) REFERENCES piloto(idPiloto)
	);

CREATE TABLE quiz (
    idQuiz INT PRIMARY KEY AUTO_INCREMENT,
    idUsuario INT, 
    acertos INT,
    erros INT,
	tentativa INT,
    tempo TIME(3),
    tipoQuiz VARCHAR(50),
    CHECK (tipoQuiz IN ('Historia', 'Equipes', 'Pilotos')),
    FOREIGN KEY (idUsuario) REFERENCES usuario(idUsuario)
);

	insert into equipe values 
	(default, "Ferrari", "https://media.formula1.com/content/dam/fom-website/teams/2024/ferrari-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/ferrari.png", "A Ferrari é a equipe mais icônica e bem-sucedida da Fórmula 1, com uma história que remonta ao início da competição em 1950. Fundada por Enzo Ferrari, a Scuderia Ferrari rapidamente se estabeleceu como uma força dominante, conquistando seu primeiro título de construtores em 1961. A equipe acumulou inúmeros títulos ao longo das décadas, com grandes pilotos como Niki Lauda, Gilles Villeneuve e Michael Schumacher, que trouxe um renascimento nos anos 2000, conquistando cinco títulos consecutivos de pilotos de 2000 a 2004. Nos últimos anos, a Ferrari tem enfrentado desafios significativos. Após a era Schumacher, a equipe teve dificuldade em recuperar a consistência necessária para conquistar campeonatos. No entanto, a chegada de jovens talentos como Charles Leclerc trouxe nova esperança. Leclerc, com sua velocidade e determinação, conquistou várias vitórias e mostrou-se uma estrela em ascensão. Em 2023, sob a liderança de Frédéric Vasseur, a Ferrari tem se concentrado em melhorias técnicas e na confiabilidade do carro, buscando reduzir a diferença para as dominantes Red Bull e Mercedes. A equipe continua a desenvolver seu motor e chassi, buscando um equilíbrio perfeito entre potência e aerodinâmica. Com investimentos contínuos em tecnologia e inovação, a Ferrari almeja retornar ao topo, onde sua rica história e tradição exigem que esteja. A Scuderia Ferrari, com sua paixão inigualável e legião de fãs, mantém vivo o sonho de reconquistar a glória máxima na Fórmula 1, honrando seu legado e pavimentando o caminho para futuras gerações de campeões."),
	(default, "Red Bull Racing", "https://media.formula1.com/content/dam/fom-website/teams/2024/red-bull-racing-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/red-bull-racing.png", "A Red Bull Racing, fundada em 2005 após a aquisição da Jaguar Racing pela gigante de bebidas energéticas Red Bull, rapidamente se tornou uma força dominante na Fórmula 1. Sob a liderança de Christian Horner e com a expertise técnica de Adrian Newey, a equipe alcançou o sucesso espetacular em pouco tempo. O piloto Sebastian Vettel foi fundamental nesse processo, conquistando quatro títulos consecutivos de pilotos de 2010 a 2013, enquanto a equipe também conquistava quatro títulos de construtores. Após um período de desafios e oscilações, a Red Bull voltou ao topo com a chegada do talentoso Max Verstappen. Em 2021, Verstappen quebrou o domínio de longo prazo da Mercedes e Lewis Hamilton, conquistando seu primeiro título mundial em uma temporada dramática e muito disputada. A equipe manteve o ímpeto, com Verstappen novamente mostrando sua classe em 2022 e 2023, solidificando sua posição como um dos melhores pilotos da atualidade. O sucesso recente da Red Bull se deve, em grande parte, à parceria com a Honda, que forneceu motores potentes e confiáveis, e à contínua inovação técnica liderada por Newey. A equipe também tem investido em jovens talentos através de seu programa de desenvolvimento, garantindo um fluxo constante de pilotos promissores. Em 2024, a Red Bull continua a ser uma força dominante, com Verstappen liderando a charge. A equipe se concentra em manter sua vantagem competitiva através de inovações aerodinâmicas e estratégias inteligentes, sempre buscando a perfeição em todos os aspectos de sua operação. Com um forte apoio da fábrica e uma base de fãs global apaixonada, a Red Bull Racing está determinada a continuar sua trajetória de sucesso e escrever novos capítulos na história da Fórmula 1."),
	(default, "McLaren", "https://media.formula1.com/content/dam/fom-website/teams/2024/mclaren-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/mclaren.png", "A McLaren, uma das equipes mais icônicas da Fórmula 1, foi fundada por Bruce McLaren em 1963. Ao longo dos anos, a equipe britânica acumulou títulos e criou lendas, com pilotos como Ayrton Senna, Alain Prost, Niki Lauda e Mika Häkkinen. A rivalidade entre Senna e Prost nos anos 80 e 90 é uma das mais memoráveis da história do esporte. Após uma era dourada, a McLaren enfrentou dificuldades para se adaptar às novas regulamentações e mudanças tecnológicas. No entanto, a parceria com a Mercedes no início dos anos 2000 trouxe nova competitividade, culminando no título de pilotos de 2008 com Lewis Hamilton. Nos últimos anos, a McLaren tem mostrado sinais de recuperação. Sob a liderança de Zak Brown e Andreas Seidl, a equipe passou por uma reestruturação profunda, focando em melhorias técnicas e operacionais. A chegada de talentos como Lando Norris e a contratação de Daniel Ricciardo trouxeram novo vigor. Em 2021, a McLaren voltou ao topo do pódio com Ricciardo vencendo o Grande Prêmio da Itália, a primeira vitória da equipe em quase uma década. Em 2023, a McLaren continua a buscar consistência e progresso, investindo em infraestrutura e desenvolvendo seu carro para competir com as equipes de ponta. Com uma base de fãs dedicada e um legado rico, a McLaren trabalha incansavelmente para reconquistar seu lugar entre os gigantes da Fórmula 1."),
	(default, "Mercedes", "https://media.formula1.com/content/dam/fom-website/teams/2024/mercedes-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/mercedes.png", "A Mercedes, uma das equipes mais dominantes da Fórmula 1 moderna, retornou ao esporte como equipe de fábrica em 2010. Sob a liderança de Toto Wolff e com a expertise técnica de engenheiros como James Allison, a equipe rapidamente se estabeleceu como uma força formidável. A parceria com a Petronas e o desenvolvimento de um motor híbrido altamente eficiente foram fundamentais para seu sucesso. A era de domínio da Mercedes começou em 2014 com a introdução dos motores híbridos turbo V6. Com Lewis Hamilton e Nico Rosberg ao volante, a equipe conquistou inúmeros títulos. Hamilton, em particular, se tornou um dos pilotos mais bem-sucedidos da história, ganhando seis campeonatos com a Mercedes entre 2014 e 2020. A rivalidade entre Hamilton e Rosberg culminou em 2016, quando Rosberg venceu o campeonato antes de se aposentar. Nos últimos anos, a Mercedes tem enfrentado desafios crescentes de equipes como Red Bull e Ferrari. Em 2021, Max Verstappen da Red Bull quebrou a sequência de títulos de Hamilton em uma temporada intensamente disputada. No entanto, a Mercedes continuou competitiva, com Hamilton e o jovem talento George Russell mostrando forte desempenho. Em 2023, a Mercedes se concentrou em recuperar sua posição dominante, investindo em inovações aerodinâmicas e melhorias no motor. A equipe também está comprometida com a sustentabilidade, promovendo iniciativas para reduzir seu impacto ambiental. Com uma base de fãs global e um histórico de sucesso, a Mercedes permanece determinada a continuar sua trajetória vitoriosa na Fórmula 1, buscando novos títulos e mantendo seu legado de excelência e inovação no esporte"),
	(default, "Aston Martin", "https://media.formula1.com/content/dam/fom-website/teams/2024/aston-martin-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/aston-martin.png", "A Aston Martin, uma marca icônica no mundo automotivo, fez seu retorno à Fórmula 1 como equipe de fábrica em 2021, após rebranding da Racing Point. Sob a liderança de Lawrence Stroll e a gestão de Otmar Szafnauer, a equipe rapidamente se estabeleceu como uma presença competitiva no grid. Com um forte apoio financeiro e uma visão clara para o futuro, a Aston Martin visa se tornar uma força dominante na F1. A chegada do tetracampeão Sebastian Vettel em 2021 trouxe experiência e talento à equipe, enquanto Lance Stroll, filho do proprietário, demonstrou seu potencial em várias corridas. O carro da Aston Martin, inicialmente baseado na plataforma da Mercedes, mostrou flashes de competitividade, embora a equipe enfrentasse desafios de consistência e desenvolvimento contínuo. Nos últimos anos, a Aston Martin tem investido significativamente em infraestrutura e tecnologia. A construção de uma nova fábrica de última geração e a contratação de talentos-chave, tanto em termos de engenharia quanto de direção, são parte da estratégia para elevar a equipe a novos patamares. Em 2023, a equipe continuou a progredir, com melhorias no chassi e no motor, buscando fechar a lacuna para as equipes líderes. A visão de longo prazo da Aston Martin é clara: tornar-se uma força dominante na Fórmula 1. Com uma combinação de investimentos estratégicos, talentos emergentes e a rica herança da marca, a equipe está bem posicionada para desafiar as equipes de ponta nos próximos anos. A base de fãs dedicada e a paixão pela excelência automotiva impulsionam a Aston Martin na busca pela glória na Fórmula 1."),
	(default, "Visa RB", "https://media.formula1.com/content/dam/fom-website/teams/2024/rb-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/rb.png", "A Scuderia AlphaTauri, anteriormente conhecida como Toro Rosso, é a equipe satélite da Red Bull Racing na Fórmula 1. A Toro Rosso foi fundada em 2006 após a aquisição da Minardi pela Red Bull, com o objetivo de desenvolver jovens talentos para a equipe principal. Desde sua criação, a Toro Rosso serviu como um campo de provas para pilotos promissores, incluindo Sebastian Vettel, que conquistou a primeira vitória da equipe no Grande Prêmio da Itália em 2008. Em 2020, a equipe foi rebatizada como AlphaTauri, em alinhamento com a marca de moda premium da Red Bull. Com a mudança, a equipe ganhou uma identidade renovada e um compromisso maior com a competitividade na F1. Pierre Gasly destacou-se ao vencer o Grande Prêmio da Itália em 2020, uma vitória marcante que solidificou a reputação da AlphaTauri como uma equipe capaz de surpreender. A AlphaTauri continua a desenvolver talentos e a inovar tecnologicamente, beneficiando-se do estreito relacionamento com a Red Bull Racing. A equipe utiliza motores da Honda, assim como a Red Bull, garantindo desempenho e confiabilidade. Em 2023, com pilotos como Yuki Tsunoda e Nyck de Vries, a AlphaTauri manteve seu foco em progredir no grid, mostrando consistência e potencial para conquistar pontos regularmente. O objetivo da AlphaTauri é claro: continuar a crescer e desafiar as equipes de meio de grid, enquanto desenvolve pilotos que possam um dia competir pela Red Bull Racing. Com investimentos contínuos em infraestrutura e tecnologia, a AlphaTauri está bem posicionada para se tornar uma força respeitável na Fórmula 1. A equipe combina a paixão pela inovação com uma tradição de desenvolvimento de talentos, refletindo o espírito competitivo e a ambição da família Red Bull no automobilismo."),
	(default, "Haas", "https://media.formula1.com/content/dam/fom-website/teams/2024/haas-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/haas.png", "A Haas F1 Team entrou na Fórmula 1 em 2016 como a primeira equipe americana na categoria em décadas. Fundada por Gene Haas, proprietário da equipe de NASCAR Stewart-Haas Racing, a equipe trouxe uma nova dinâmica para o grid da F1. A abordagem inovadora da Haas incluiu uma parceria técnica com a Ferrari, visando maximizar recursos e acelerar o desenvolvimento do carro. Antes de sua estreia como equipe, a Haas teve uma longa história no automobilismo como patrocinadora de equipes como a Stewart Grand Prix na década de 1990 e a equipe de F1 da Lola na década de 1980. No entanto, foi apenas em 2016 que a Haas estabeleceu sua própria equipe, com base nos Estados Unidos, mas com operações na Europa para aproveitar a expertise técnica disponível. Nos primeiros anos, a Haas impressionou com sua abordagem pragmática e sua capacidade de pontuar consistentemente. No entanto, a falta de recursos e a dependência da parceria com a Ferrari apresentaram desafios, especialmente em termos de desenvolvimento de longo prazo. A equipe manteve seu compromisso com os jovens talentos, oferecendo oportunidades para pilotos como Romain Grosjean, Kevin Magnussen e Mick Schumacher. Em 2023, a Haas continuou sua jornada na Fórmula 1, buscando melhorias de desempenho e estabilidade financeira. Com uma nova abordagem para o desenvolvimento do carro e investimentos estratégicos, a equipe está determinada a subir no grid e desafiar equipes rivais. A Haas representa não apenas a entrada dos Estados Unidos na F1, mas também a busca contínua por excelência e competitividade em um dos esportes mais desafiadores do mundo"),
	(default, "Williams","https://media.formula1.com/content/dam/fom-website/teams/2024/williams-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/williams.png", "A Williams Racing, uma das equipes mais icônicas da Fórmula 1, tem uma história rica que remonta aos primórdios do esporte. Fundada por Sir Frank Williams em 1977, a equipe se tornou sinônimo de excelência e sucesso. Antes de estabelecer sua própria equipe, Williams teve uma carreira no automobilismo, incluindo a co-fundação da equipe Frank Williams Racing Cars na década de 1960. Ao longo dos anos, a Williams conquistou múltiplos títulos de pilotos e construtores, destacando-se como uma das equipes mais bem-sucedidas da história da F1. Pilotos lendários como Alan Jones, Nelson Piquet, Nigel Mansell, Alain Prost, Damon Hill e Jacques Villeneuve trouxeram glória à equipe, conquistando campeonatos e vitórias memoráveis. No entanto, nas últimas duas décadas, a Williams enfrentou dificuldades em manter sua posição de destaque no grid. Mudanças na liderança, falta de recursos financeiros e desafios técnicos contribuíram para um declínio no desempenho da equipe. A parceria com a BMW na década de 2000 trouxe algum sucesso, mas a Williams continuou a lutar para competir com as equipes de ponta. Em 2020, a Williams foi adquirida pela empresa de investimentos Dorilton Capital, marcando um novo capítulo em sua história. Sob nova gestão, a equipe busca revitalizar sua competitividade e reconstruir sua reputação na F1. Com investimentos estratégicos e uma abordagem renovada para o desenvolvimento do carro, a Williams está determinada a retornar aos dias de glória e desafiar as equipes rivais no grid. A Williams representa não apenas uma história de sucesso no automobilismo, mas também uma busca contínua por excelência e resiliência em face de desafios."),
	(default, "Alpine","https://media.formula1.com/content/dam/fom-website/teams/2024/alpine-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/alpine.png", "A Alpine F1 Team, anteriormente conhecida como Renault F1 Team, tem raízes profundas na Fórmula 1, remontando à sua entrada no esporte como equipe de fábrica em 1977. A equipe foi inicialmente fundada como Toleman Motorsport, antes de se tornar Benetton Formula nos anos 1980 e 1990, conquistando títulos de pilotos e construtores com Michael Schumacher. Em 2002, a equipe foi renomeada como Renault F1 Team, marcando uma nova era de sucesso. Sob a liderança de Flavio Briatore e com pilotos como Fernando Alonso, a Renault conquistou campeonatos mundiais de pilotos e construtores em 2005 e 2006. A equipe foi reconhecida por sua inovação técnica e consistência no desempenho. Nos anos seguintes, a Renault passou por altos e baixos, enfrentando desafios de competitividade e mudanças na estrutura organizacional. Em 2021, a equipe foi rebatizada como Alpine F1 Team, em homenagem à marca de automóveis de alta performance da Renault. A mudança representou uma nova fase para a equipe, com um foco renovado em conquistar sucesso tanto nas pistas quanto fora delas. Com Esteban Ocon e Fernando Alonso como pilotos em 2023, a Alpine está determinada a desafiar as equipes de ponta e recuperar sua posição como uma força dominante na Fórmula 1. Com uma combinação de tradição, inovação e paixão pelo esporte, a Alpine representa o compromisso contínuo da Renault com o automobilismo de elite e a busca pela excelência em todas as áreas."),
	(default, "Kick Sauber", "https://media.formula1.com/content/dam/fom-website/teams/2024/kick-sauber-logo.png", "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2024/kick-sauber.png", "A Kick Sauber, anteriormente conhecida como Alfa Romeo Racing ORLEN F1 Team, tem uma história rica e diversificada na Fórmula 1. Fundada por Peter Sauber em 1993, a equipe suíça entrou no esporte como equipe privada e rapidamente se estabeleceu como uma competidora respeitável. Antes de se tornar a Sauber, a equipe foi conhecida como BMW Sauber F1 Team de 2006 a 2009, quando teve uma colaboração técnica com a montadora alemã. Durante seus primeiros anos na F1, a Sauber conquistou vários pódios e mostrou um forte desempenho em uma série de temporadas. No entanto, enfrentou desafios financeiros e de recursos que limitaram seu progresso. Em 2018, a equipe foi renomeada como Alfa Romeo Racing, em uma parceria com a marca italiana de automóveis, refletindo uma nova era para a equipe. Com uma abordagem renovada e uma parceria técnica com a Ferrari, a Alfa Romeo Racing ORLEN busca melhorar seu desempenho e desafiar as equipes de ponta. Com Kimi Räikkönen e Guanyu Zhou como pilotos em 2023, a equipe está determinada a aproveitar ao máximo seu potencial e competir no mais alto nível. A Alfa Romeo Racing ORLEN representa a tradição, a paixão e o compromisso com o automobilismo, enquanto continua a escrever seu capítulo na história da Fórmula 1. Em 2026, a equipe dá um passo rumo ao futuro, pois torna-se Audi, após a montadora decidir aumentar sua participação no time suíço de 75% para 100%, encerrando rumores de um possível abandono do projeto. Essa mudança marca uma nova fase emocionante para a equipe, trazendo consigo expectativas renovadas e um olhar para um futuro promissor.");

	insert into piloto values 
	(1, 16, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CHALEC01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png", "Charles Leclerc", "1997-10-16", null, 1, "Nascido no idílio mediterrâneo de Mônaco, Charles Leclerc chegou à F1 com altas expectativas após dominar a GP3 e a Fórmula 2. Sua jornada foi marcada por pole positions impressionantes, vitórias emocionantes e a habilidade de lidar com pressão. Na Ferrari desde 2019, Leclerc não hesitou em duelar com Sebastian Vettel, conquistando vitórias emblemáticas em Spa e Monza. Apesar das temporadas difíceis em 2020 e '21, ele emergiu como um forte candidato ao título em 2022, desafiando consistentemente Max Verstappen. Fora das pistas, Leclerc é modesto e reflexivo, correndo em homenagem a seu pai e a seu amigo Jules Bianchi. Seus resultados até agora certamente os deixariam orgulhosos"),
    (2, 55, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/CARSAI01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png", "Carlos Sainz", "1994-09-01", null, 1, "Carlos Sainz, o 'matador da realeza das corridas de Madrid', entrou na Fórmula 1 ao lado de Max Verstappen na Toro Rosso em 2015, demonstrando desde cedo seu espírito combativo. Conhecido como 'Chilli', Sainz é agressivo e inteligente, conquistando pontos com sua habilidade de levar o carro ao limite e pensar estrategicamente durante as corridas. Filho do bicampeão mundial de rali Carlos Sainz, ele herdou suas habilidades de condução, mostrando-se habilidoso tanto dentro quanto fora das pistas. Após passagens pela McLaren e agora na Ferrari, Sainz enfrentou o desafio de substituir ícones como Fernando Alonso e Sebastian Vettel, mas demonstrou determinação ao conquistar vitórias pela Scuderia."),
    (3, 1, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/MAXVER01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png", "Max Verstappen", "1997-09-30", 3, 2, "Max Verstappen é conhecido por sua natureza determinada e talento excepcional desde que se tornou o mais jovem piloto da Fórmula 1 aos 17 anos. Com uma abordagem instintiva e corajosa, ele rapidamente se destacou na Toro Rosso e, posteriormente, na Red Bull. Verstappen tornou-se o mais jovem vencedor de corridas na história da F1 aos 18 anos, demonstrando seu potencial em condições desafiadoras no Brasil. Sua jornada teve altos e baixos, mas sua maturidade e habilidade inegável o levaram ao título mundial em 2021 e a uma defesa bem-sucedida em 2022. Filho do ex-piloto Jos Verstappen e da talentosa Sophie Kumpen, Max tem a corrida em seu sangue. Apesar de sua determinação nas pistas, ele mantém uma conexão próxima com sua família, mostrando-se tanto corajoso quanto modesto. Sua conquista como o primeiro campeão mundial holandês aos 24 anos elevou as expectativas sobre sua carreira, mas com Verstappen, o potencial parece ilimitado"),
    (4, 11, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/SERPER01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png", "Sergio Perez", "1990-01-26", null, 2, "Sergio Perez, conhecido como o lutador com uma abordagem gentil da terra da Lucha Libre, construiu sua reputação na F1 com uma mistura única de agressão e suavidade. Ele é um combatente agressivo nas pistas, nunca com medo de lutar pelo pelotão e pelos pontos, às vezes até esquentando as coisas com seus companheiros de equipe. Por outro lado, é um mestre em gerenciar pneus, estratégias e trabalhar em equipe. Com passagens por Sauber, McLaren, Force India e Racing Point, Perez acumulou mais pontos do que qualquer outro mexicano na história da F1. Seu destaque veio em Sakhir 2020, onde venceu pela primeira vez, igualando seu herói Pedro Rodriguez. Na Red Bull, tem sido um forte suporte para Verstappen, contribuindo com cinco vitórias próprias. Embora um desafio pelo título possa ser difícil ao lado de Verstappen, Perez continua trabalhando duro e correndo com paixão..."),
    (5, 4, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANNOR01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png", "Lando Norris", "1999-11-13", null, 3, "Lando Norris pode não ser nomeado em homenagem ao rebelde de Star Wars, Lando Calrissian - sua mãe simplesmente gostava do nome - mas ele tem talento e espírito de luta em abundância. A McLaren tinha o adolescente britânico em seus livros por dois anos antes de acelerá-lo para a galáxia de estrelas da F1 em 2019. Um foguete em sua carreira júnior, com uma inclinação para pole positions e lutas roda a roda, Norris não decepcionou. Ao lado do altamente avaliado - e muito mais experiente - Carlos Sainz, sua temporada de estreia foi impressionante, Norris superando o espanhol na batalha de classificação direta, marcando pontos 11 vezes e perdendo por pouco um lugar no top 10 do campeonato. Um primeiro pódio veio em 2020, com mais seguindo nas duas temporadas subsequentes - ele perdeu por pouco uma vitória na Rússia em 2021 - enquanto ele dominava outro companheiro de equipe mais experiente, Daniel Ricciardo, para firmar seu lugar na elite da F1. Fora da pista, Norris transborda com um charme modesto e um lado artístico que o vê desenhar e pintar seu próprio equipamento de corrida como um hobby. O foco para o futuro é aliar arte e ambição na pista, enquanto a McLaren conta com a promessa da juventude para levá-los de volta ao topo. Norris espera que a força aerodinâmica esteja com ele..."),
    (6, 81, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/OSCPIA01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png", "Oscar Piastri", "2001-06-04", null, 3, "Oscar Piastri, nascido em Melbourne, teve seu desejo de competir na Fórmula 1 inspirado pelos Grandes Prêmios locais. Sua jornada exigiu mudança para a Europa, seguindo os passos de Mark Webber e Daniel Ricciardo. Após sucesso no karting australiano, Piastri avançou para campeonatos europeus de monopostos, mostrando promessa desde os 15 anos. Rapidamente, ele conquistou títulos na F4, Formula Renault, F3 e F2, com uma vantagem impressionante no último. Seu desempenho chamou a atenção de equipes de F1, com a McLaren garantindo seus serviços para 2023. Sua estreia na categoria foi marcada por dois pódios notáveis, destacando seu potencial como uma estrela em ascensão."),
    (7, 44, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LEWHAM01.png", "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png", "Lewis Hamilton", "1985-01-07", 7, 4, "Still I Rise - são as palavras estampadas na parte de trás do capacete de Lewis Hamilton e tatuadas em seus ombros, e desde que aniquilou as expectativas com uma das maiores performances de estreia na história da F1 em 2007, é literalmente tudo o que ele tem feito: subido ao topo da lista de pole positions de todos os tempos à frente de seu herói Ayrton Senna, avançado para o primeiro lugar na lista de vitórias ultrapassando o inimitável Michael Schumacher e depois igualado aos sete títulos mundiais do lendário alemão. Ele é o G.O.A.T? Poucos negariam que ele está na conversa - e o que é mais, ele chegou lá do seu jeito, combinando sua velocidade implacável com uma recusa em se conformar com estereótipos sobre como um piloto de corrida deve pensar, se vestir ou se comportar. O respeito é conquistado com dificuldade na F1, mas Hamilton - Sir Lewis Hamilton para ser preciso - o tem de todos os seus pares. Por quê? Porque eles sabem que, seja qual for a pista, seja qual for a condição, seja qual for a situação, quando seu visor desce e as luzes se apagam, é a hora de Hamilton."),
	(8, 63, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GEORUS01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png", "George Russell", "1998-02-15", null, 4, "George Russell, conhecido por sua abordagem destemida, rapidamente deixou sua marca na Fórmula 1. Dominando sua temporada de estreia contra Robert Kubica, ele revigorou a Williams e conquistou uma vitória impressionante com a Mercedes em 2022. Sua jornada rumo ao sucesso na F1 foi marcada por triunfos na GP3 e na Fórmula 2, chamando a atenção da Mercedes desde cedo. A determinação inabalável de Russell ficou evidente quando ele substituiu Lewis Hamilton de última hora, quase garantindo a vitória no Bahrein. Apesar dos contratempos, sua resiliência brilhou, culminando em uma vitória memorável no Brasil. Enquanto enfrenta desafios em 2023, o potencial de Russell para disputar o campeonato permanece, dependendo do ressurgimento da Mercedes. Sua história personifica perseverança e aproveitamento de oportunidades, preparando o cenário para um futuro emocionante no automobilismo."),
	(9, 14, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/FERALO01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png", "Fernando Alonso", "1981-07-29", 2, 5, "Michael Schumacher dominou a Fórmula 1 nos anos 2000, mas Fernando Alonso emergiu como seu desafiante mais formidável. Conhecido por sua competitividade feroz e talento inegável, Alonso foi um quebrador de recordes em seus primeiros dias, conquistando pole positions, vitórias e títulos mundiais com a Renault. Apesar de passagens pela McLaren e Ferrari, não adicionou mais títulos à sua coleção. Após dois anos afastado, retornou com a Alpine em 2021, mostrando velocidade e determinação, embora frustrado pela confiabilidade. Agora na Aston Martin, busca voltar às vitórias, determinado a resolver seus negócios inacabados na F1."),
	(10, 18, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LANSTR01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png", "Lance Stroll", "1998-10-29", null, 5, "Lance Stroll desafia a ideia de 'muito rápido, muito cedo', emergindo como uma sensação adolescente na F1, especialmente em corridas sob chuva. Revelado pela Williams logo após completar 18 anos, ele estabeleceu recordes em sua temporada de estreia, incluindo um pódio em Baku, tornando-se o mais jovem estreante a fazê-lo. Filho de um empresário rico, Stroll está familiarizado com luxos, mas valoriza ainda mais o pódio. Sua determinação foi evidente em Monza, onde se tornou o mais jovem a largar na primeira fila. Ágil na primeira volta e lutando consistentemente pelos pontos, Stroll mostrou seu potencial com sua primeira pole position e dois pódios em 2020. Com seu pai liderando a transformação da Force India para Aston Martin, o futuro parece promissor para a equipe e seu jovem piloto, que não se intimida nem mesmo pela chuva, continuando a acelerar na frente do pelotão."),
	(11, 22, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/YUKTSU01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png", "Yuki Tsunoda", "2000-05-11", null, 6, "Na história inteira da Fórmula 1, nenhum piloto japonês jamais venceu um Grande Prêmio do Campeonato Mundial. Yuki Tsunoda poderia ser o primeiro? A Red Bull certamente pensa assim, com o jovem muito no caminho para sua equipe principal se ele continuar a impressionar como tem feito nos últimos anos. A ascensão de Tsunoda ao topo do automobilismo foi surpreendentemente rápida: ele passou de correr na F4 japonesa para um assento na Fórmula 1 com a AlphaTauri, agora RB, em pouco mais de três anos, depois de ter chegado à Europa em 2019 sem conhecimento das pistas. Mas depois de um começo lento na F3, seguido por uma campanha de estreia na F2 muito impressionante que o viu terminar em terceiro no campeonato e conquistar três vitórias pelo caminho, Tsunoda provou que tinha a velocidade e a habilidade de corrida para conquistar seu lugar no grid da F1. Ele pode não ter se adaptado às corridas de Grand Prix tão rapidamente quanto se adaptou à F2, mas agora que ele se estabeleceu firmemente na Fórmula 1, ele ainda pode se encontrar lutando na ponta do pelotão em um Red Bull."),
	(12, 3, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/DANRIC01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png", "Daniel Ricciardo", "1989-07-01", null, 6, "Daniel Ricciardo, conhecido como 'Honey Badger', é um piloto que combina charme e agressividade nas pistas. Por trás de seu sorriso cativante, há um competidor feroz, sempre pronto para ultrapassar os limites. Com sua habilidade de corrida impressionante, ele se destacou na Red Bull, celebrando no pódio com sua tradicional 'Shoey', uma expressão da cultura australiana. Suas mudanças para Renault e depois para McLaren trouxeram desafios, mas seu objetivo de ser campeão mundial permanece. Após um breve afastamento, Ricciardo retornou à Red Bull como terceiro piloto e agora está na AlphaTauri, determinado a competir ao lado de Max Verstappen. Independentemente do que o futuro reserva, seu sorriso característico continuará brilhando."),
	(13, 27, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/NICHUL01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png", "Nico Hülkenberg", "1987-08-19", null, 7, "Nico Hulkenberg, apelidado de 'Hulk' da F1, demonstrou uma incrível força e resistência ao longo de sua carreira, competindo por várias equipes desde 2010. Sua estreia na F1 foi marcada por uma impressionante pole position no Brasil, mostrando sua habilidade em condições de pista desafiadoras. Reconhecido por acumular consistentemente pontos, ele também ganhou destaque ao vencer as 24 Horas de Le Mans em sua primeira tentativa. Fora das pistas, Hulkenberg é conhecido por sua personalidade pé no chão e senso de humor peculiar. Apesar de não ter alcançado um pódio na F1, sua popularidade e talento continuam evidentes, especialmente após suas corridas destacadas como substituto em 2020 e 2022. Agora, com um retorno em tempo integral pela Haas, ele está determinado a fazer valer sua oportunidade."),
	(14, 20, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/KEVMAG01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/KEVMAG01_Kevin_Magnussen/kevmag01.png", "Kevin Magnussen", "1992-10-05", null, 7, "Kevin Magnussen, conhecido por sua abordagem solitária e rebelde na pista, tem um único objetivo na Fórmula 1: correr. Como filho de Jan Magnussen, ele é parte da segunda geração de pilotos da F1, mas sua inspiração vem da 'era dourada' do automobilismo. Sua habilidade foi evidenciada quando conquistou um pódio em sua estreia pela McLaren em 2014, tornando-se o primeiro dinamarquês a fazê-lo. Após passagens pela Renault e quatro temporadas na Haas, Magnussen teve um ano nos Estados Unidos antes de retornar à Haas em 2022, garantindo a primeira pole position da equipe no Brasil. Conhecido por suas manobras ousadas e abordagem agressiva, ele tem uma reputação de bad boy na pista, algo que ele não compreende completamente. Fora do carro, Magnussen é descontraído e afável, desfrutando do emprego dos sonhos e focado exclusivamente em correr."),
	(15, 23, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ALEALB01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png", "Alexander Albon", "1996-03-23", null, 8, "Nascido em Londres, Alexander Albon cresceu sonhando em correr na Fórmula 1, inspirado por Michael Schumacher. Depois de uma batalha pelo título na GP3 em 2016 e na Fórmula 2 em 2018, ele estreou na F1 em 2019 com a Toro Rosso, sendo promovido para a Red Bull no meio da temporada. Demonstrou habilidade como ultrapassador, mas teve dificuldades em manter o ritmo de Max Verstappen em 2020, sendo retirado da equipe. Permanecendo como piloto de teste e reserva, retornou à grid em 2022 com a Williams, mostrando rapidez nas classificações e maturidade como piloto. Descontraído e popular entre os colegas, Albon encara o desafio de aproveitar ao máximo sua segunda oportunidade na F1."),
	(16, 24, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/LOGSAR01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LOGSAR01_Logan_Sargeant/logsar01.png", "Logan Sargeant", "2000-12-31", null, 8, "Logan Sargeant tornou-se o primeiro piloto americano da Fórmula 1 em quase oito anos na temporada de 2023, trazendo de volta a empolgação para os fãs dos Estados Unidos. Com uma carreira de sucesso no kartismo, sua transição para monopostos foi marcada por pole positions e vitórias em várias categorias, incluindo F4 e F3. Seu desempenho consistente na F2 chamou a atenção da Williams, que o contratou para a temporada de 2023. Embora tenha pontuado apenas uma vez em sua temporada de estreia, ele está determinado a explorar seu potencial na F1. Com três corridas nos EUA no calendário, Sargeant tem o apoio de sua torcida em casa."),
	(17, 10, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/PIEGAS01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png", "Pierre Gasly", "1996-02-07", null, 9, "Pierre Gasly é um especialista em reviravoltas na carreira na Fórmula 1. Sua jornada começou em 2017, quando substituiu Daniil Kvyat na Toro Rosso. Destaques, como um quarto lugar no Bahrein em 2018, levaram-no à Red Bull no ano seguinte. No entanto, ele lutou com comparações desfavoráveis com Max Verstappen e foi relegado de volta à Toro Rosso. Gasly se recuperou com força, terminando em segundo no Brasil. Em 2020, conquistou uma emocionante vitória na Itália e continuou a impressionar em 2021, marcando a maioria dos pontos da AlphaTauri. Mudou-se para a Alpine em 2022, buscando um novo impulso em sua carreira. O desafio agora é manter o ritmo e alcançar novamente a grandeza na F1."),
	(18, 31, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/ESTOCO01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png", "Esteban Ocon", "1996-09-17", null, 9, "Esteban Ocon personifica o sacrifício em sua carreira na Fórmula 1. Seus pais venderam sua casa e suspenderam seus empregos para apoiar sua carreira desde os dias de kart. Em 2014, ele venceu Max Verstappen para conquistar o título da Fórmula 3 Europeia, seguido pelo título da GP3 em 2015, com apoio da Mercedes. Em 2016, ele substituiu Rio Haryanto na Manor e garantiu um assento em tempo integral na Force India em 2017. No entanto, foi afastado no final do ano para dar lugar a Lance Stroll. Após um ano como piloto reserva da Mercedes, Ocon retornou à grid em 2020 com a Renault, agora Alpine, onde conquistou sua primeira vitória na F1 em 2021. Sua jornada foi marcada por autoconfiança, determinação e talento excepcional."),
	(19, 77, "https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/VALBOT01.png", "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png", "Valtteri Bottas", "1989-08-28", null, 10, "Valtteri Bottas é um verdadeiro piloto finlandês, aprendendo nas estradas geladas e nevadas de sua terra natal. Sua estreia na Fórmula 1 com a Williams em 2013 marcou o início de uma jornada marcada por pontos e pódios, embora sem uma vitória. Sua habilidade confiável o levou à Mercedes em 2017, onde ele floresceu, conquistando pole positions, vitórias e um campeonato de equipe ao lado de Lewis Hamilton. Apesar de uma temporada difícil em 2018, Bottas recuperou o ritmo em 2019, terminando em segundo lugar no campeonato. No entanto, seu desempenho diminuiu em 2020 e 2021, levando à sua dispensa da Mercedes. Em 2022, ele começou um novo capítulo na Alfa Romeo, liderando a equipe e mentorando o estreante Zhou Guanyu."),
	(20, 24, 'https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/GUAZHO01.png', 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GUAZHO01_Guanyu_Zhou/guazho01.png', 'Zhou Guanyu', '1999-05-30', NULL, 10, 'Zhou Guanyu fez história ao se tornar o primeiro piloto chinês a competir na Fórmula 1, representando a Alfa Romeo em 2022. Desde uma idade precoce, Zhou foi apaixonado por corridas, tendo assistido ao Grande Prêmio de Xangai quando criança e torcido por Fernando Alonso. Determinado a se tornar o primeiro piloto chinês na F1, ele se mudou para a Inglaterra aos 12 anos para seguir sua carreira no automobilismo. Com o apoio da academia de pilotos da Ferrari e, posteriormente, da Renault, Zhou competiu na Fórmula 2, acumulando vitórias e pole positions ao longo de três temporadas. Sua performance impressionante chamou a atenção de Fred Vasseur, chefe de equipe da Alfa Romeo, que decidiu dar a Zhou a chance de realizar seu sonho na F1 em 2022. Ao lado de Valtteri Bottas, Zhou enfrentou o desafio de competir na categoria máxima do automobilismo e até mesmo competir contra seu herói de infância, Fernando Alonso.'),
    (21, 38, 'https://media.formula1.com/d_default_fallback_image.png/content/dam/fom-website/2018-redesign-assets/drivers/number-logos/OLIBEA01.png', 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png', 'Oliver Bearman', '2005-05-08', NULL, 1, 'Oliver Bearman fez sua estreia surpreendente na Fórmula 1 durante o Grande Prêmio da Arábia Saudita, substituindo Carlos Sainz, que estava fora devido a apendicite. Aos 18 anos, Bearman é o reserva oficial da Ferrari e teve seu primeiro contato com os carros de Fórmula 1 no final do ano anterior, durante treinos livres 1 pela equipe Haas nos Grandes Prêmios do México e Abu Dhabi. Embora seja relativamente novo na cena da F1, Bearman já acumulou experiência em testes e competições na Fórmula 2 com a equipe Prema Racing. Sua habilidade foi demonstrada por suas quatro vitórias e sua posição de sexto na classificação da F2 no ano anterior. Após uma pole position impressionante em Jeddah, Bearman teve que interromper temporariamente sua campanha na F2 para assumir as responsabilidades de substituição de Sainz. Sua estreia na F1 foi marcada por uma performance notável, garantindo um sétimo lugar e seis pontos, o que certamente aumentou suas perspectivas futuras na categoria máxima do automobilismo.');
        

    

		